name: Auto Checkin
on:
  # GitHub Actions 使用国际标准时间，与国内相差 8 小时，设置时注意避雷
  # 详细语法参见 https://www.runoob.com/linux/linux-comm-crontab.html
  schedule:
    - cron: '*/30 20-21 * * *'  # 此处设置为北京时间 4:00、4:30、5:00、5:30 共尝试四次
  watch:
    types: [started]  # 也可以通过手动对项目 star 来触发
jobs:
  checkin:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install basic modules
        run: 'pip3 install -r requirements.txt'

      - name: Install pytorch
        run: 'pip3 install torch==1.10.2+cpu torchvision==0.11.3+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html'

      - name: Auto checkin
        env:
          USER: ${{ secrets.USER }}
        run: python main.py
